# Generated by Django 6.0.5 on 2026-05-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo_barra', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono_emergencia', models.CharField(max_length=20)),
                ('notas_medicas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
