# Generated by Django 6.0.5 on 2026-05-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(max_length=50, unique=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono_emergencia', models.CharField(max_length=20)),
                ('notas_medicas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
