# Generated by Django 6.0.5 on 2026-05-26 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=50)),
                ('duracion_dias', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Membresiacliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_membresia', models.CharField(choices=[('Vigente', 'Vigente'), ('Vencida', 'Vencida'), ('Cancelada', 'Cancelada')], default='Vigente', max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('plan_suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.plansuscripcion')),
            ],
        ),
    ]
